name: Mocking test

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    workflow_dispatch:

jobs:
  example-3:
    name: Mocking test
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v4
      - uses: nanasess/setup-chromedriver@v2
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: anaconda-client-env
          environment-file: environment.yml
          python-version: 3.12
          auto-activate-base: false
      - run: |
          conda info
          conda list
      - name: Set environment variable and run tests
        env:
          MOCKING: true
        run: |
          pytest
