name: Mocking test

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    workflow_dispatch:

jobs:
  basic_tests:
    name: Mocking test
    runs-on: "ubuntu-latest"
    steps:
      - name: Check out repositroy
        uses: actions/checkout@v4
      - name: Set up Conda environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: anaconda-client-env
          environment-file: environment.yml
          python-version: 3.12
          auto-activate-base: false
      - run: |
          conda info
          conda list
      - name: Install browser dependencies
        run: |
          pip install chromedriver-autoinstaller pyvirtualdisplay
          sudo apt-get install xvfb
      - name: Set environment variable and run tests
        env:
          MOCKING: true
        run: |
          pytest
