name: Mocking test

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    workflow_dispatch:

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 5
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v4
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
        conda config --add channels defaults
    - name: Install dependencies
      run: |
        conda install -y python=${{ matrix.python-version }}
        conda env update --file environment.yml --name base
        # pip install chromedriver-autoinstaller pyvirtualdisplay
    - name: Set up environment and run tests
      env:
        MOCKING: true
      run: |
        # export DISPLAY=:99
        # Xvfb :99 &
        pytest
