name: Mocking test

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - uses: conda-incubator/setup-miniconda@v3
              with:
                activate-environment: mirte-itl
                environment-file: environment.yml
                auto-activate-base: false
            - run: |
                conda activate mirte-itl
                conda info
                conda list
            - name: Run tests
              env:
                MOCKING: True
              run: |
                conda activate mirte-itl
                pytest
